export const GET_ALL_COMPETITIONS = 'GET_ALL_COMPETITIONS';
export const GET_COMPETITION_DETAIL = 'GET_COMPETITION_DETAIL';
export const ADD_COMPETITION = 'ADD_COMPETITION';
export const UPDATE_COMPETITION = 'UPDATE_COMPETITION';
export const DELETE_COMPETITION = 'DELETE_COMPETITION';