export const GET_ALL_EXHIBITIONS = "GET_ALL_EXHIBITIONS";
export const GET_EXHIBITION_DETAIL = "GET_EXHIBITION_DETAIL";
export const ADD_EXHIBITION = "ADD_EXHIBITION";
export const UPDATE_EXHIBITION = "UPDATE_EXHIBITION";
export const DELETE_EXHIBITION = "DELETE_EXHIBITION";
export const SEARCH_EXHIBITIONS = "SEARCH_EXHIBITIONS";
