export const GET_ALL_EXHIBITION_SUBMISSIONS = "GET_ALL_EXHIBITION_SUBMISSIONS";
export const GET_EXHIBITION_SUBMISSION_DETAIL = "GET_EXHIBITION_SUBMISSION_DETAIL";
export const ADD_EXHIBITION_SUBMISSION = "ADD_EXHIBITION_SUBMISSION";
export const UPDATE_EXHIBITION_SUBMISSION = "UPDATE_EXHIBITION_SUBMISSION";
export const DELETE_EXHIBITION_SUBMISSION = "DELETE_EXHIBITION_SUBMISSION";
export const SEARCH_EXHIBITION_SUBMISSIONS = "SEARCH_EXHIBITION_SUBMISSIONS";
