export const GET_ALL_SUBMISSIONS = 'GET_ALL_SUBMISSIONS';
export const GET_SUBMISSION_DETAIL = 'GET_SUBMISSION_DETAIL';
export const ADD_SUBMISSION = 'ADD_SUBMISSION';
export const UPDATE_SUBMISSION = 'UPDATE_SUBMISSION';
export const DELETE_SUBMISSION = 'DELETE_SUBMISSION';
export const SEARCH_SUBMISSIONS = 'SEARCH_SUBMISSIONS';
