export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST';
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS';
export const CREATE_PAYMENT_FAILURE = 'CREATE_PAYMENT_FAILURE';

export const PAYMENT_CALLBACK_REQUEST = 'PAYMENT_CALLBACK_REQUEST';
export const PAYMENT_CALLBACK_SUCCESS = 'PAYMENT_CALLBACK_SUCCESS';
export const PAYMENT_CALLBACK_FAILURE = 'PAYMENT_CALLBACK_FAILURE';
